# name: Update Release Notes

# on:
#   push:
#     branches:
#       - main  # Change this to your branch name

# jobs:
#   update-release-notes:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v2

#       - name: Read commit message
#         id: read-commit-message
#         run: echo "::set-output name=message::$(cat commit_message.txt)"

#       - name: Read description
#         id: read-description
#         run: echo "::set-output name=description::$(cat description.txt)"

#       - name: Create Release
#         id: create-release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: Release ${{ github.ref }}
#           body: |
#             Commit Message: ${{ steps.read-commit-message.outputs.message }}
#             Description: ${{ steps.read-description.outputs.description }}
#           draft: false
#           prerelease: false


#           name: Generate Release Notes


name: Publish Release Notes

on:
  push:
    branches:
      - main

jobs:
  publish_release_notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read Release Notes
      id: read_release_notes
      run: |
        # Example: Read release notes from a file
        RELEASE_NOTES=$(cat README.md)
        echo "::set-output name=notes::$RELEASE_NOTES"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: "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"
      with:
        tag_name: v1.0.0  # Specify your release tag here
        release_name: Release v1.0.0  # Specify your release name here
        body: ${{ steps.read_release_notes.outputs.notes }}  # Use the release notes from the previous step
        draft: false
        prerelease: false

