name: Update Release Notes

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  update-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Read release notes
        id: read-notes
        run: echo "::set-output name=notes::$(cat release_notes.txt)"

      - name: Append release notes to release-drafter.yml
        run: |
          echo "- ${{ steps.read-notes.outputs.notes }}" >> .github/release-drafter.yml

      - name: Commit and push changes
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add .github/release-drafter.yml
          git commit -m "Update release notes"
          git push
