name: Generate Release Notes
on:
  push:
    branches:
      - main

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Read content from md file
        id: read_readme
        run: |
          README_CONTENT=$(cat README.md)
          echo "::set-output name=content::$README_CONTENT"

      - name: Extract version from README.md
        id: extract_version
        run: echo "${{ steps.read_readme.outputs.content }}"

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Increment Tag
        id: increment_tag
        run: |
            current_tag="${{ steps.get_latest_tag.outputs.latest_tag }}"
            IFS='.' read -r -a parts <<< "$current_tag"
            major="${parts[0]}"
            minor="${parts[1]}"
            patch="${parts[2]}"
            patch=$((patch+1))
            next_tag="$major.$minor.$patch"
            echo "::set-output name=next_tag::$next_tag"
  
      - name: Publish Release Note
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment_tag.outputs.next_tag }}
          release_name: Release ${{ steps.increment_tag.outputs.next_tag }}
          body: |
            Commit Message: ${{ github.event.head_commit.message }}
            README Content: ${{ steps.read_readme.outputs.content }}