name: Create a new release note

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release-note:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generated content
        id: gen_note
        uses: ./
        with:
          kind: default
          tag-pattern: v*
          current-tag: ${{ github.ref }}

      - name: Create a new release note
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: ${{ steps.gen_note.outputs.summary }}
          draft: false
          prerelease: false
