name: Publish Release Notes

on:
  push:
    branches:
      - main

jobs:
  publish_release_notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read Release Notes
      id: read_release_notes
      run: |
        # Example: Read release notes from a file
        RELEASE_NOTES=$(cat README.md)
        echo "::set-output name=notes::$RELEASE_NOTES"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0  # Specify your release tag here
        release_name: Release v1.0.0  # Specify your release name here
        body: ${{ steps.read_release_notes.outputs.notes }}  # Use the release notes from the previous step
        draft: false
        prerelease: false
