name: Publish Release Notes

on:
  push:
    branches:
      - main


jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3

  create-release-notes:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          OUTPUT_FOLDER: temp_release_notes

      - name: Upload Release Notes to Wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          ACTION_MAIL: YOUR_EMAIL
          ACTION_NAME: NAME_OF_THE_USER_WHO_PUBLISH
          GH_PAT: "${{ secrets.GITHUB_TOKEN }}"
          MD_FOLDER: temp_release_notes
          OWNER: parul
          REPO_NAME: gitactions
          SKIP_MD: README.md